version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: 'rabbitmq'
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=InventorySync
      - RABBITMQ_DEFAULT_PASS=SyncInventory
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}]
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
